//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebAPI.DataAccess.dbContext
{
    using System;
    using System.Collections.Generic;
   
    public partial class Cars
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public bool IsSell { get; set; }
        public int BrandId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsConfirmed { get; set; }
    
        public virtual Brands Brands { get; set; }
    }
}
